global:
  scrape_interval: 5s     # How often to scrape targets by default
  evaluation_interval: 5s # How often to evaluate rules

scrape_configs:
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape your Spring PetClinic app
  - job_name: 'spring-petclinic'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['spring-petclinic-app:8080']
